version: "3"
services:
  caddy:
    restart: always
    image: caddy:2.4.6
    container_name: caddy
    ports:
      - 8080:8080
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./app:/srv
      - ./files:/files
      - ./logs:/var/log
volumes:
  caddy_data: 
  caddy_config:
