version: "3"
services:
  caddy:
    restart: always
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - 9001:9001
      - 9002:9002

    volumes:
      - ./app-one:/var/www/app-one
      - ./app-two:/var/www/app-two
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data: 
  caddy_config:
